version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    networks:
      - p2p_network
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    expose:
      - "8000/udp" 

  node2:
    build: .
    container_name: node2
    networks:
      - p2p_network
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    expose:
      - "8000/udp"


networks:
  p2p_network:
    driver: bridge
