services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client1
    expose:
      - "8000/udp" # Makes 8000/udp visible to other containers on the same network
    networks:
      - p2p-net
    # TODO: remove hardcoded port
    command: just run 8000 log1.log
  client2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client2
    expose:
      - "8000/udp"
    networks:
      - p2p-net
    # TODO: remove hardcoded port
    command: just run 8000 log2.log
networks:
  p2p-net:
    driver: bridge
